(GET) https://api-capstone-heroku.herokuapp.com/admin/rawat_jalan_lihat

poli yang tersedia sebagai parameter: Gigi, Kandungan, THT, Umum

respon:
{
    "code": 200,
    "data": [
        {
            "id": 40,
            "nik": "0000000000000000001",
            "nama": "tester1",
            "alamat": "tester1",
            "jenis_kelamin": "L",
            "jadwal_rawat_jalan": "Senin, 4 Juli 2022 Pukul 08.00 WIB",
            "nomer_antrian": "U-1",
            "proses": true,
            "keterangan": "",
            "no_hp": "000000000001",
            "tempat_lahir": "tester1",
            "tanggal_lahir": "1 Januari 2000",
            "jenis_penyakit": "",
            "jenis_penanganan": "Rawat jalan"
        },
        {
            "id": 34,
            "nik": "35111105057530210",
            "nama": "Ali Zainul",
            "alamat": "Jl KH Wahid Hasyim no 10 RT 30 RW 09 Malang",
            "jenis_kelamin": "L",
            "jadwal_rawat_jalan": "",
            "nomer_antrian": "T-1",
            "proses": false,
            "keterangan": "",
            "no_hp": "082122019283",
            "tempat_lahir": "Malang",
            "tanggal_lahir": "2022-07-05",
            "jenis_penyakit": "",
            "jenis_penanganan": "Rawat jalan"
        },
        {
            "id": 35,
            "nik": "35111105057530293",
            "nama": "Fathan Abdulhalim",
            "alamat": "Jl KH Wahid Hasyim no 10 RT 30 RW 09 Malang",
            "jenis_kelamin": "L",
            "jadwal_rawat_jalan": "",
            "nomer_antrian": "K-1",
            "proses": false,
            "keterangan": "",
            "no_hp": "082122019283",
            "tempat_lahir": "Malang",
            "tanggal_lahir": "7 Desember 1994",
            "jenis_penyakit": "",
            "jenis_penanganan": "Rawat jalan"
        },
        {
            "id": 41,
            "nik": "0000000000000000002",
            "nama": "tester2",
            "alamat": "tester2",
            "jenis_kelamin": "L",
            "jadwal_rawat_jalan": "Senin, 4 Juli 2022 Pukul 08.00 WIB",
            "nomer_antrian": "U-2",
            "proses": true,
            "keterangan": "",
            "no_hp": "000000000002",
            "tempat_lahir": "tester2",
            "tanggal_lahir": "2 Januari 2000",
            "jenis_penyakit": "",
            "jenis_penanganan": "Rawat jalan"
        },
        {
            "id": 42,
            "nik": "0000000000000000003",
            "nama": "tester3",
            "alamat": "tester3",
            "jenis_kelamin": "L",
            "jadwal_rawat_jalan": "Senin, 4 Juli 2022 Pukul 08.00 WIB",
            "nomer_antrian": "U-3",
            "proses": true,
            "keterangan": "",
            "no_hp": "000000000003",
            "tempat_lahir": "tester3",
            "tanggal_lahir": "3 Januari 2000",
            "jenis_penyakit": "",
            "jenis_penanganan": "Rawat jalan"
        },
        {
            "id": 43,
            "nik": "0000000000000000004",
            "nama": "tester4",
            "alamat": "tester4",
            "jenis_kelamin": "L",
            "jadwal_rawat_jalan": "Senin, 4 Juli 2022 Pukul 08.00 WIB",
            "nomer_antrian": "U-4",
            "proses": true,
            "keterangan": "",
            "no_hp": "000000000004",
            "tempat_lahir": "tester4",
            "tanggal_lahir": "4 Januari 2000",
            "jenis_penyakit": "",
            "jenis_penanganan": "Rawat jalan"
        },
        {
            "id": 44,
            "nik": "000000000000000005",
            "nama": "tester5",
            "alamat": "tester5",
            "jenis_kelamin": "L",
            "jadwal_rawat_jalan": "Senin, 4 Juli 2022 Pukul 08.00 WIB",
            "nomer_antrian": "U-5",
            "proses": true,
            "keterangan": "",
            "no_hp": "000000000005",
            "tempat_lahir": "tester5",
            "tanggal_lahir": "5 Januari 2000",
            "jenis_penyakit": "",
            "jenis_penanganan": "Rawat jalan"
        },
        {
            "id": 45,
            "nik": "00000000000000006",
            "nama": "tester6",
            "alamat": "tester6",
            "jenis_kelamin": "L",
            "jadwal_rawat_jalan": "Senin, 4 Juli 2022 Pukul 08.00 WIB",
            "nomer_antrian": "U-6",
            "proses": true,
            "keterangan": "",
            "no_hp": "000000000006",
            "tempat_lahir": "tester6",
            "tanggal_lahir": "6 Januari 2000",
            "jenis_penyakit": "",
            "jenis_penanganan": "Rawat jalan"
        },
        {
            "id": 37,
            "nik": "35111105057101141",
            "nama": "Trisna Chandra Laksana",
            "alamat": "Jl Manchester no 4 RT 04 RW 04 United Kingdom",
            "jenis_kelamin": "L",
            "jadwal_rawat_jalan": "",
            "nomer_antrian": "G-2",
            "proses": true,
            "keterangan": "",
            "no_hp": "082122010235",
            "tempat_lahir": "Sueabaya",
            "tanggal_lahir": "15 September 2004",
            "jenis_penyakit": "",
            "jenis_penanganan": "Rawat jalan"
        },
        {
            "id": 36,
            "nik": "35111105057530007",
            "nama": "Naufal Ulwan",
            "alamat": "Jl KH Wahid Hasyim no 10 RT 30 RW 09 Malang",
            "jenis_kelamin": "L",
            "jadwal_rawat_jalan": "",
            "nomer_antrian": "G-1",
            "proses": true,
            "keterangan": "",
            "no_hp": "082122019283",
            "tempat_lahir": "Malang",
            "tanggal_lahir": "7 Desember 1994",
            "jenis_penyakit": "",
            "jenis_penanganan": "Rawat jalan"
        },
        {
            "id": 38,
            "nik": "1397004847029237",
            "nama": "Yessenia Mitchell I",
            "alamat": "Apt. 914 17447 Raymundo Valley, Hoppeside, DE 16645-7433",
            "jenis_kelamin": "wanita",
            "jadwal_rawat_jalan": "",
            "nomer_antrian": "U-1",
            "proses": true,
            "keterangan": "",
            "no_hp": "",
            "tempat_lahir": "Melvinmouth",
            "tanggal_lahir": "Sat Nov 02 05:06:26 ICT 1957",
            "jenis_penyakit": "",
            "jenis_penanganan": "Rawat jalan"
        },
        {
            "id": 39,
            "nik": "35111105057530215",
            "nama": "Nurhuda Bikhoir",
            "alamat": "Jl KH Wahid Hasyim no 10 RT 30 RW 09 Malang",
            "jenis_kelamin": "L",
            "jadwal_rawat_jalan": "",
            "nomer_antrian": "U-2",
            "proses": true,
            "keterangan": "",
            "no_hp": "082122019283",
            "tempat_lahir": "Malang",
            "tanggal_lahir": "7 Desember 1994",
            "jenis_penyakit": "",
            "jenis_penanganan": "Rawat jalan"
        },
        {
            "id": 46,
            "nik": "00000000000000007",
            "nama": "tester7",
            "alamat": "tester7",
            "jenis_kelamin": "L",
            "jadwal_rawat_jalan": "Senin, 4 Juli 2022 Pukul 08.00 WIB",
            "nomer_antrian": "U-7",
            "proses": false,
            "keterangan": "",
            "no_hp": "000000000007",
            "tempat_lahir": "tester7",
            "tanggal_lahir": "7 Januari 2000",
            "jenis_penyakit": "",
            "jenis_penanganan": "Rawat jalan"
        },
        {
            "id": 47,
            "nik": "00000000000000008",
            "nama": "tester8",
            "alamat": "tester8",
            "jenis_kelamin": "L",
            "jadwal_rawat_jalan": "Senin, 4 Juli 2022 Pukul 08.00 WIB",
            "nomer_antrian": "U-8",
            "proses": false,
            "keterangan": "",
            "no_hp": "000000000008",
            "tempat_lahir": "tester8",
            "tanggal_lahir": "8 Januari 2000",
            "jenis_penyakit": "",
            "jenis_penanganan": "Rawat jalan"
        }
    ]
}

